# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 853d2167e1a9fb60fd43e758737b54bec0cb94a790087f7c6b1bfb8bdb3c29fcd76e1c1c8da85255e0a18bf48e380f1fc273b1885e5f735afd352efcd9129c5c

test:
  secret_key_base: a6ce9b60bd7a80bc68e685da8c1a7ac05f23b47c8e8d2c71d661bd908d704f70be00b772488691c21067224eed0b99b6643f75eca46c2e9430a021de9fbe9a4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
